blank_issues_enabled: true
contact_links:
  - name: FlashCoin Core Security Policy
    url: https://github.com/FlashCoin/FlashCoin/blob/master/SECURITY.md
    about: View security policy
  - name: FlashCoin Core Developers
    url: https://FlashCoincore.org
    about: FlashCoin Core homepage
